name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
      
        with:
          node-version: ${{ matrix.node-version }}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "friendin-deed"
          heroku_email: "sanyambharani07@gmail.com"
          usedocker: true
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm test
